name: Run TFLint check

on:
  - push

permissions:
  contents: write

jobs:
  tflint-check:
    name: Run TFLint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Cache plugin dir
        uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          # key: tflint-${{ hashFiles('.tflint.hcl') }}
          key: tflint-plugins

      - name: Show version
        run: |
          tflint --version

      - name: Run check modules
        run: |
          cd modules
          for f in * ; do
            if [ -d "$f" ] ; then
              cd $f
              tflint --init
              tflint --format=compact --no-color
              cd ..
            fi
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Run TFLint check
